/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MenuCategory = { 'dessert' : null } |
  { 'starter' : null } |
  { 'main' : null };
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : MenuCategory,
  'priceCents' : bigint,
}
export type MenuItemId = bigint;
export interface ReservationRequest {
  'date' : string,
  'name' : string,
  'time' : string,
  'email' : string,
  'notes' : string,
  'partySize' : bigint,
}
export interface RestaurantInfo {
  'about' : string,
  'hours' : string,
  'tagline' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addMenuItem' : ActorMethod<
    [string, string, bigint, MenuCategory, boolean],
    MenuItemId
  >,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllReservationRequests' : ActorMethod<[], Array<ReservationRequest>>,
  'getMenuItemsByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getRestaurantInfo' : ActorMethod<[], RestaurantInfo>,
  'removeMenuItem' : ActorMethod<[MenuItemId], undefined>,
  'seedMenuItems' : ActorMethod<[], undefined>,
  'submitReservationRequest' : ActorMethod<
    [string, string, string, string, bigint, string],
    undefined
  >,
  'updateMenuItem' : ActorMethod<
    [MenuItemId, string, string, bigint, MenuCategory, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];