/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuCategory = IDL.Variant({
  'dessert' : IDL.Null,
  'starter' : IDL.Null,
  'main' : IDL.Null,
});
export const MenuItemId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : MenuCategory,
  'priceCents' : IDL.Nat,
});
export const ReservationRequest = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'partySize' : IDL.Nat,
});
export const RestaurantInfo = IDL.Record({
  'about' : IDL.Text,
  'hours' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, MenuCategory, IDL.Bool],
      [MenuItemId],
      [],
    ),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllReservationRequests' : IDL.Func(
      [],
      [IDL.Vec(ReservationRequest)],
      ['query'],
    ),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  'removeMenuItem' : IDL.Func([MenuItemId], [], []),
  'seedMenuItems' : IDL.Func([], [], []),
  'submitReservationRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateMenuItem' : IDL.Func(
      [MenuItemId, IDL.Text, IDL.Text, IDL.Nat, MenuCategory, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuCategory = IDL.Variant({
    'dessert' : IDL.Null,
    'starter' : IDL.Null,
    'main' : IDL.Null,
  });
  const MenuItemId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : MenuCategory,
    'priceCents' : IDL.Nat,
  });
  const ReservationRequest = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'partySize' : IDL.Nat,
  });
  const RestaurantInfo = IDL.Record({
    'about' : IDL.Text,
    'hours' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, MenuCategory, IDL.Bool],
        [MenuItemId],
        [],
      ),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllReservationRequests' : IDL.Func(
        [],
        [IDL.Vec(ReservationRequest)],
        ['query'],
      ),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
    'removeMenuItem' : IDL.Func([MenuItemId], [], []),
    'seedMenuItems' : IDL.Func([], [], []),
    'submitReservationRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateMenuItem' : IDL.Func(
        [MenuItemId, IDL.Text, IDL.Text, IDL.Nat, MenuCategory, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };