/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    id: MenuItemId;
    name: string;
    description: string;
    available: boolean;
    category: MenuCategory;
    priceCents: bigint;
}
export interface ReservationRequest {
    date: string;
    name: string;
    time: string;
    email: string;
    notes: string;
    partySize: bigint;
}
export type MenuItemId = bigint;
export interface RestaurantInfo {
    about: string;
    hours: string;
    tagline: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export enum MenuCategory {
    dessert = "dessert",
    starter = "starter",
    main = "main"
}
export interface backendInterface {
    addMenuItem(name: string, description: string, priceCents: bigint, category: MenuCategory, available: boolean): Promise<MenuItemId>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllReservationRequests(): Promise<Array<ReservationRequest>>;
    getMenuItemsByCategory(category: MenuCategory): Promise<Array<MenuItem>>;
    getRestaurantInfo(): Promise<RestaurantInfo>;
    removeMenuItem(id: MenuItemId): Promise<void>;
    seedMenuItems(): Promise<void>;
    submitReservationRequest(name: string, email: string, date: string, time: string, partySize: bigint, notes: string): Promise<void>;
    updateMenuItem(id: MenuItemId, name: string, description: string, priceCents: bigint, category: MenuCategory, available: boolean): Promise<void>;
}
import type { MenuCategory as _MenuCategory, MenuItem as _MenuItem, MenuItemId as _MenuItemId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMenuItem(arg0: string, arg1: string, arg2: bigint, arg3: MenuCategory, arg4: boolean): Promise<MenuItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2, to_candid_MenuCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2, to_candid_MenuCategory_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReservationRequests(): Promise<Array<ReservationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReservationRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReservationRequests();
            return result;
        }
    }
    async getMenuItemsByCategory(arg0: MenuCategory): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(to_candid_MenuCategory_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(to_candid_MenuCategory_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurantInfo(): Promise<RestaurantInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurantInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurantInfo();
            return result;
        }
    }
    async removeMenuItem(arg0: MenuItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMenuItem(arg0);
            return result;
        }
    }
    async seedMenuItems(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedMenuItems();
            return result;
        }
    }
    async submitReservationRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReservationRequest(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReservationRequest(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItemId, arg1: string, arg2: string, arg3: bigint, arg4: MenuCategory, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, to_candid_MenuCategory_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, to_candid_MenuCategory_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
}
function from_candid_MenuCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuCategory): MenuCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MenuItemId;
    name: string;
    description: string;
    available: boolean;
    category: _MenuCategory;
    priceCents: bigint;
}): {
    id: MenuItemId;
    name: string;
    description: string;
    available: boolean;
    category: MenuCategory;
    priceCents: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        available: value.available,
        category: from_candid_MenuCategory_n6(_uploadFile, _downloadFile, value.category),
        priceCents: value.priceCents
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dessert: null;
} | {
    starter: null;
} | {
    main: null;
}): MenuCategory {
    return "dessert" in value ? MenuCategory.dessert : "starter" in value ? MenuCategory.starter : "main" in value ? MenuCategory.main : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n4(_uploadFile, _downloadFile, x));
}
function to_candid_MenuCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): _MenuCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): {
    dessert: null;
} | {
    starter: null;
} | {
    main: null;
} {
    return value == MenuCategory.dessert ? {
        dessert: null
    } : value == MenuCategory.starter ? {
        starter: null
    } : value == MenuCategory.main ? {
        main: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
